### ISSUE TITLE
React 0.14.0 refs changes

### ISSUE THREAD

**Issue by NeXTs** [eiriklv/react-packery-mixin#5]
Hi!
React team have recently [released v0.14.0](https://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html) and it exposing refs to DOM components as the DOM node itself so we don't need call .getDOMNode() anymore to get access to DOM element.
this.refs.elemName already contains it.

My console is full of

> Warning: ReactDOMComponent: Do not access .getDOMNode() of a DOM node; instead, use the node directly. This DOM node was rendered by `Packery`.

Please consider this and remove .getDOMNode() from sources.
Thanks in advance!

**Comment by eiriklv** [comment]
@NeXTs If you have time - feel free to submit a PR and merge it right in :-)

**Comment by eiriklv** [comment]
Because this will affect backwards compatibility I'll have to release a new major version and make this clear in the readme

**Comment by NeXTs** [comment]
> Because this will affect backwards compatibility

That's why I decided to leave it for you, otherwise I'd made PR of course :)
